name: Build Develop

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - run: mv dist sta-ng
      - uses: action/upload-artifact@v3
        with:
          path: sta-ng