name: Build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - run: |
          cd dist
          zip -r -9 sta-ng.zip sta-ng
      - uses: actions/upload-artifact@v3
        with:
          name: sta-ng.zip
          path: ${{ github.workspace }}/dist/sta-ng.zip