name: Build Prerelease

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - run: |
          mv dist sta-ng
          zip -r -9 sta-ng.zip sta-ng
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: sta-ng.zip
          generateReleaseNotes: true
          name: develop
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}